version: 2.1
# Use a package of configuration called an orb.
orbs:
 aws-cli: circleci/aws-cli@2.0.3
# Define the jobs we want to run for this project
jobs:
  myjob1:  # Choose any name, such as `build`
      docker:
        - image:  amazon/aws-cli
      steps:
        - checkout
        - run: 
            name: create-infrastructre
            command: |
             aws cloudformation deploy \
                --template-file templet.yml \
                --stack-name myStack-${CIRCLE_WORKFLOW_ID:0:5} \
                --region us-east-1

  configure_infrastructure: 
    docker:
    - image: python:3.7-alpine3.11
    steps: 
    - checkout
    - add_ssh_keys:
        fingerprints:
          - "27:ea:1d:01:43:e3:51:65:48:f2:3a:e3:df:f8:51:71"
    - run:
       name: Install Ansible    
       command: | 
        apk add --update ansible \
        inventory \
        main-remot.yml \





# Sequential workflow
workflows:
  # Name the workflow
  myWorkflow:
    jobs:
      - myjob1
      - configure_infrastructure